version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: gown-database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  server:
    build: ./server
    container_name: gown-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  client:
    build: ./client
    container_name: gown-client
    ports:
      - "3000:80"  # Client available at localhost:3000
    env_file:
      - .env
    depends_on:
      - server

  initdb:
    build: ./server
    container_name: gown-initdb
    command: ["node", "/app/database/init.js"]
    working_dir: /app
    volumes:
      - ./server:/app
      - ./database:/app/database
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    restart: "no"

volumes:
  mysql_data:
